apiVersion: v1
kind: Namespace
metadata:
  name: galah

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: galah-deployment
  namespace: galah
  labels:
    app: galah
spec:
  replicas: 1
  selector:
    matchLabels:
      app: galah
  template:
    metadata:
      labels:
        app: galah
    spec:
      containers:
      - name: galah
        image: infosecb/galah:latest
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api-key
              key: api_key
        ports:
        - containerPort: 8080
        - containerPort: 8443
        - containerPort: 8888
        - containerPort: 443

---

apiVersion: v1
kind: Service
metadata:
  name: galah-service
  namespace: galah
spec:
  selector:
    app: galah
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: https-alt
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: http-alt
      protocol: TCP
      port: 8888
      targetPort: 8888
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443